### ISSUE TITLE
No progress bar when trail length = 0

### ISSUE THREAD

**Issue by WavyHertZ** [bsondermann/BlackboxSticksExporter3D#5]
In settings, when trail length = 0 (because i don't like trails so it's like i'm disabling them)
And then when i render, it skip the traoms render (good), but for the "rendering 3D sticks" there is no progress bar neither the count down timer, only the timer for time passed.

**Comment by bsondermann** [comment]
Hi, can you send me the blackbox log you were using?

**Comment by WavyHertZ** [comment]
Yes sure : https://we.tl/t-vSwX7ioT6W

**Comment by bsondermann** [comment]
Hi. You are right, there is a bug with the process bar but the rendering itself does still work and the final video will be successfully exported. I will fix the bug in the next update, thanks!
btw. very nice pid tune :)

**Comment by WavyHertZ** [comment]
Okay nice ! Awesome software, keep it up
Ahah thanks ^^
